const userData = {
  githubUsername: "blazingyeti",
  name: "Blazing Yeti",
  description: "Tech Projects",
  siteUrl: "https://blazingyeti.com/",
  domainHost: "blazingyeti.com",
  statsHost: "https://plausible.io",
  heroDescription: "I dabble in tech projects and code. Mostly Python and Javascript.",
  avatarUrl: "logo.png",
  email: "admin@blazingyeti.com",
  keywords: [
    "Tech",
    "Tech Projects",
    "Javascript",
    "Python",
    "Databases",
    "React",
    "Svelte",
    "Web3",
  ],
  projects: [
    {
      title: "10ktf Rarity",
      repoName: "10ktf-rarity",
      link: "https://github.com/blazingyeti/10ktf-rarity",
      demo: "https://10ktf-rarity.xyz",
      imgUrl: "../10ktf-rarity.png",
      tags: ["React", "Javascript", "Bootstrap"],
    },
    {
      title: "WordTrak",
      repoName: "wordtrak",
      link: "https://github.com/blazingyeti/wordtrak",
      demo: "http://wordtrak.s3-website.us-east-2.amazonaws.com/",
      imgUrl: "../wordtrak.png",
      tags: ["Svelte", "Javascript", "Tailwind CSS"],
    },
    {
      title: "NFT Gallery",
      repoName: "nft-gallery",
      link: "https://github.com/blazingyeti/nft-gallery",
      demo: "https://github.com/blazingyeti/nft-gallery",
      imgUrl: "../nft-gallery.png",
      tags: ["React", "Javascript", "Bootstrap", "EthersJS", "Alchemy"],
    },
    {
      title: "React Web3 Example",
      repoName: "react-web3-example",
      link: "https://github.com/blazingyeti/react-web3-example",
      demo: "https://blazingyeti.github.io/react-web3-example",
      imgUrl: "../react-web3-example.gif",
      tags: ["React", "Javascript", "Bootstrap", "EthersJS"],
    },
    {
      title: "IPFS React Example",
      repoName: "ipfs-react-example",
      link: "https://github.com/blazingyeti/ipfs-react-example",
      demo: "https://github.com/blazingyeti/ipfs-react-example",
      imgUrl: "../ipfs-react-example.png",
      tags: ["React", "Javascript", "Bootstrap", "NFT.Storage"],
    },
  ],
  about: {
    title: "dabbler in tech and development",
    description: [
      `Career in Data and Databases`,
      `Hobbyist in Web Development`,
      `Dabbling in GameDev and WebAssembly`,
      `Also Dabbled in Web3 and Crypto`,
    ],
    currentProject: "WordTrak",
    currentProjectUrl: "http://wordtrak.s3-website.us-east-2.amazonaws.com/",
  },
  socialLinks: {
    twitter: "https://twitter.com/blazingyeti",
    github: "https://github.com/blazingyeti",
  },
};

export default userData;
